add new-branch
defaultnastia/project-digital-dragons-money-guard pull request #19
Opened 2024-07-16 21:36 UTC by AntonM88

Сподіваюсь на цей раз ок)

2024-07-16 22:39 UTC, defaultnastia commented on src/App.tsx
в цьому файлі ти зачистив зайве

2024-07-16 22:41 UTC, defaultnastia commented on src/components/CustomButton/CustomButton.tsx
цей файл ти теж не збирався змінювати

2024-07-16 22:42 UTC, defaultnastia commented on src/components/CustomModal/CustomModal.module.css
будь-ласка, впевнись що ці зміни не конфліктують зі змінами Нікіти і що тут саме те що треба

2024-07-16 22:42 UTC, defaultnastia commented on src/components/CustomModal/CustomModal.tsx
будь-ласка, впевнись що ці зміни не конфліктують зі змінами Нікіти і що тут саме те що треба

2024-07-16 22:48 UTC, AntonM88 commented on src/components/CustomModal/CustomModal.tsx
буде зроблено!

2024-07-16 22:53 UTC, defaultnastia commented on src/img/icons.svg
тут таки не вистачає як мінімум однієї іконки з плюсом, та що в Нікіти на add transaction

2024-07-16 23:00 UTC, defaultnastia requested changes
будь-ласка, перевір все по коментам і перед ти як віддати - стягни зміни з мейну

2024-07-17 07:53 UTC, defaultnastia approved these changes
Svg and Icon's fill and stroke will be done in future commits

2024-07-17 07:53 UTC, merged